<a href="https://colab.research.google.com/github/BrunoWLP/Atividades-Carnaval/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Atividades de Carnaval 🥳

### Concentra mas Numpy

In [1]:
import numpy as np

In [3]:
# Criando um vetor com os seguintes valores [1,2,3,4,5], chame-o de vetA

vetA = np.array([1, 2, 3, 4, 5])
vetA

array([1, 2, 3, 4, 5])

In [4]:
# Exiba os 3 primeiros elementos

vetA[:3]

array([1, 2, 3])

In [5]:
# Exiba todos os valores após o quinto elemento

vetA[5:]

array([], dtype=int64)

In [6]:
# Exiba os 3 últimos elementos

vetA[-3:]

array([3, 4, 5])

In [17]:
# Exiba os valores de vetA entre o 5 elemento até o penúltimo elemento

print(vetA[4:-1])

#Prova com outro array maior:
vetB = np.array([1, 2, 3, 4, 5, 6, 7, 8])
vetB[4:-1]

[]


array([5, 6, 7])

In [67]:
# Crie uma matriz 5x5 e exiba a matriz inteira

# 1:
a = np.arange(25).reshape(5, 5)
print(a)
print()

# 2:
b = np.zeros((5, 5))
print(b)
print()

# 3:
ary1 = np.array([1, 2, 3, 4, 5])
ary2 = np.array([6, 7, 8, 9, 10])
c = np.matrix([ary1, ary2, ary1, ary2, ary1])
print(c)
print()

# 4:
d = np.matrix('1 2 3 4 5; 6 7 8 9 10; 1 2 3 4 5; 6 7 8 9 10; 1 2 3 4 5')
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [46]:
# Exiba todos os elementos da coluna 3

a[:, 2]

array([ 2,  7, 12, 17, 22])

In [47]:
# Exiba todos os elementos da linha 2

a[1, :]

array([5, 6, 7, 8, 9])

In [48]:
# Exiba todos os elementos das 2 primeiras colunas

a[: , :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [49]:
# Exiba todos os elementos das 2 primeiras linhas:

a[:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
# Exiba Apenas os elementos das 2 últimas linhas e das 4 últimas colunas

a[-2:, :]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# Crie uma função que receba dois vetores e realize a soma de seus valores

def soma(v1, v2):
  return v1 + v2



In [68]:
print(a)
print('-'*20)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [69]:
soma(a, c)

matrix([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [21, 23, 25, 27, 29]])

In [82]:
# Generalize a função acima para que ela receba uma string representando a operação a ser executada: '+' ou '-'

def operacao(v1, v2, operacao):
  '''
  param v1/v2: vetores de mesmo tamanho.
  param operacao: 'soma' para somar os vetores; 'sub' para subtraí-los.
  '''
  if operacao.lower() == 'soma':
    return v1 + v2
  elif operacao.lower() == 'sub':
    return v1 - v2
  return print('Insira a operação correta: SOMA ou SUB')

    

In [77]:
help(operacao)

Help on function operacao in module __main__:

operacao(v1, v2, operacao)
    param v1/v2: vetores de mesmo tamanho.
    param operacao: 'soma' para somar os vetores; 'sub' para subtrair



In [84]:
operacao(a, c, 'sobe')

Insira a operação correta: SOMA ou SUB


In [85]:
print(operacao(a, c, 'sub'))
print()
print(operacao(a, c, 'soma'))

[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [ 9  9  9  9  9]
 [ 9  9  9  9  9]
 [19 19 19 19 19]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [21 23 25 27 29]]




Calcule apenas a média das colunas

In [87]:
# Calcular a média dos valores de uma matriz

print(a)
print('Média: ', a.mean())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Média:  12.0


In [114]:
# Calcule apenas a média das linhas

print(a.mean(axis=1))
print(np.average(a, axis=1))


[ 2.  7. 12. 17. 22.]
[ 2.  7. 12. 17. 22.]


In [115]:
# Calcule apenas a média das colunas

print(a.mean(axis=0))
print(np.average(a, axis=0))

[10. 11. 12. 13. 14.]
[10. 11. 12. 13. 14.]
